# =============================================================================
# Dash — Platform Mode (OpenHands Server + Database)
# =============================================================================
#
# This runs the full OpenHands platform which provides:
#   - Web UI with chat, terminal, file editor, and browser panels
#   - Sandboxed runtime for bash, file editing, Python scripts
#   - Dash context injected via .openhands_instructions
#
# Usage:
#   docker compose -f compose.platform.yaml up -d
#   open http://localhost:3000
#
# The agent will automatically load Dash's context (6 layers of knowledge,
# SQL rules, data quality gotchas) from .openhands_instructions.
#
# The database is accessible from the sandbox via host.docker.internal:5432
# =============================================================================

services:
  dash-db:
    image: pgvector/pgvector:pg17
    container_name: dash-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-ai}
      POSTGRES_PASSWORD: ${DB_PASS:-ai}
      POSTGRES_DB: ${DB_DATABASE:-ai}

  # Custom sandbox image — build with: docker compose -f compose.platform.yaml build dash-sandbox
  dash-sandbox:
    build:
      context: .
      dockerfile: Dockerfile.sandbox
    image: dash-sandbox:latest
    profiles: ["build"]   # only used for building, not running

  openhands:
    image: docker.openhands.dev/openhands/openhands:latest
    container_name: openhands-dash
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      # Docker socket — OpenHands needs this to create sandbox containers
      - /var/run/docker.sock:/var/run/docker.sock
      # Persistent state (conversations, settings)
      - openhands-state:/.openhands
      # Dash skills — auto-loaded into every conversation's agent context
      - ./skills/dash-agent.md:/app/skills/dash-agent.md:ro
      - ./skills/dash-schema.md:/app/skills/dash-schema.md:ro
      - ./skills/dash-sql-patterns.md:/app/skills/dash-sql-patterns.md:ro
    environment:
      # Use our custom sandbox image with psql pre-installed
      AGENT_SERVER_IMAGE_REPOSITORY: dash-sandbox
      AGENT_SERVER_IMAGE_TAG: latest
      # Mount the Dash workspace into every sandbox container
      # Files available at /workspace/ — agent reads .openhands_instructions
      SANDBOX_VOLUMES: "${PWD:-.}:/workspace:rw"
      # NOTE: Do NOT set LLM_API_KEY or DB_* env vars here — they conflict
      # with the server's internal LiteLLM proxy. Configure the LLM via
      # the Settings page in the UI (http://localhost:3000).
    extra_hosts:
      # So sandbox containers can reach the database via host.docker.internal
      - "host.docker.internal:host-gateway"

volumes:
  pgdata:
  openhands-state:
