# =============================================================================
# Dash — Platform Mode (OpenHands Server + Database)
# =============================================================================
#
# This runs the full OpenHands platform which provides:
#   - Web UI with chat, terminal, file editor, and browser panels
#   - Sandboxed runtime for bash, file editing, Python scripts
#   - Dash context injected via .openhands_instructions
#
# Usage:
#   docker compose -f compose.platform.yaml up -d
#   open http://localhost:3000
#
# The agent will automatically load Dash's context (6 layers of knowledge,
# SQL rules, data quality gotchas) from .openhands_instructions.
#
# The database is accessible from the sandbox via host.docker.internal:5432
# =============================================================================

services:
  dash-db:
    image: pgvector/pgvector:pg17
    container_name: dash-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-ai}
      POSTGRES_PASSWORD: ${DB_PASS:-ai}
      POSTGRES_DB: ${DB_DATABASE:-ai}

  openhands:
    image: docker.openhands.dev/openhands/openhands:latest
    container_name: openhands-dash
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      # Docker socket — OpenHands needs this to create sandbox containers
      - /var/run/docker.sock:/var/run/docker.sock
      # Persistent state (conversations, settings)
      - openhands-state:/.openhands
    environment:
      # Workspace — OpenHands mounts this host directory into sandbox containers
      WORKSPACE_BASE: ${PWD:-.}
      # LLM configuration (configure once here, not per-conversation in UI)
      LLM_API_KEY: ${LLM_API_KEY:-${OPENAI_API_KEY}}
      LLM_MODEL: ${LLM_MODEL:-openai/gpt-4.1}
      # NOTE: Do NOT set DB_* env vars here — OpenHands interprets them as
      # its own database config. The agent learns the DB connection info from
      # .openhands_instructions in the workspace instead.
    extra_hosts:
      # So sandbox containers can reach the database via host.docker.internal
      - "host.docker.internal:host-gateway"

volumes:
  pgdata:
  openhands-state:
