# =============================================================================
# Dash — Platform Mode (OpenHands Server + Database)
# =============================================================================
#
# This runs the full OpenHands platform which provides:
#   - Web UI with chat, terminal, file editor, and browser panels
#   - Sandboxed runtime for bash, file editing, Python scripts
#   - All of Dash's custom SQL tools (run_sql, introspect_schema, etc.)
#
# Usage:
#   docker compose -f compose.platform.yaml up -d
#
# Then either:
#   1. Open http://localhost:3000 in your browser (OpenHands Web UI)
#   2. python -m dash.platform  (CLI connecting to the platform)
#
# See README.md for full documentation.
# =============================================================================

services:
  dash-db:
    image: pgvector/pgvector:pg17
    container_name: dash-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-ai}
      POSTGRES_PASSWORD: ${DB_PASS:-ai}
      POSTGRES_DB: ${DB_DATABASE:-ai}
    networks:
      - dash

  openhands-server:
    image: ghcr.io/all-hands-ai/openhands:latest
    container_name: openhands-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      # Mount Docker socket so OpenHands can create sandboxed containers
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount the Dash workspace so it's accessible in the sandbox
      - .:/opt/workspace/dash
      - openhands-state:/opt/openhands/state
    environment:
      # LLM configuration (passed through to the agent)
      LLM_API_KEY: ${LLM_API_KEY:-${OPENAI_API_KEY}}
      LLM_MODEL: ${LLM_MODEL:-openai/gpt-4.1}
      # Database configuration (accessible from within the sandbox)
      DB_HOST: dash-db
      DB_PORT: 5432
      DB_USER: ${DB_USER:-ai}
      DB_PASS: ${DB_PASS:-ai}
      DB_DATABASE: ${DB_DATABASE:-ai}
      # Tracing (optional)
      LMNR_PROJECT_API_KEY: ${LMNR_PROJECT_API_KEY:-}
    depends_on:
      - dash-db
    networks:
      - dash
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  dash:

volumes:
  pgdata:
  openhands-state:
